apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort


---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: react_lab/backend:latest
        imagePullPolicy: Never
        env: 
        - name: BACKEND_ADDRESS
          value: :5000
        - name: PROJECT_ROOT_PATH
          value: '/home/guest'
        ports:
        - containerPort: 5000