// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AppMap               map[string]*App `protobuf:"bytes,2,rep,name=app_map,json=appMap,proto3" json:"app_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetAppMap() map[string]*App {
	if m != nil {
		return m.AppMap
	}
	return nil
}

type App struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PageMap              map[string]*Page `protobuf:"bytes,4,rep,name=page_map,json=pageMap,proto3" json:"page_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{1}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *App) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *App) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *App) GetPageMap() map[string]*Page {
	if m != nil {
		return m.PageMap
	}
	return nil
}

type Page struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num                  int32                 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	ComponentMap         map[string]*Component `protobuf:"bytes,3,rep,name=component_map,json=componentMap,proto3" json:"component_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{2}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Page) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Page) GetComponentMap() map[string]*Component {
	if m != nil {
		return m.ComponentMap
	}
	return nil
}

type Component struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position             *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Size                 *Size     `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Args                 string    `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{3}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Component) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Component) GetSize() *Size {
	if m != nil {
		return m.Size
	}
	return nil
}

func (m *Component) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{4}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Size struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{5}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Size) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type Data struct {
	UserMap              map[string]*User `protobuf:"bytes,1,rep,name=user_map,json=userMap,proto3" json:"user_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{6}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetUserMap() map[string]*User {
	if m != nil {
		return m.UserMap
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterMapType((map[string]*App)(nil), "api.User.AppMapEntry")
	proto.RegisterType((*App)(nil), "api.App")
	proto.RegisterMapType((map[string]*Page)(nil), "api.App.PageMapEntry")
	proto.RegisterType((*Page)(nil), "api.Page")
	proto.RegisterMapType((map[string]*Component)(nil), "api.Page.ComponentMapEntry")
	proto.RegisterType((*Component)(nil), "api.Component")
	proto.RegisterType((*Position)(nil), "api.Position")
	proto.RegisterType((*Size)(nil), "api.Size")
	proto.RegisterType((*Data)(nil), "api.Data")
	proto.RegisterMapType((map[string]*User)(nil), "api.Data.UserMapEntry")
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor_5ab9ba5b8d8b2ba5) }

var fileDescriptor_5ab9ba5b8d8b2ba5 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xd5, 0xfa, 0x23, 0x75, 0x26, 0x49, 0x55, 0x56, 0x50, 0x59, 0x41, 0x40, 0x64, 0x21, 0x14,
	0x2e, 0x16, 0x14, 0x0e, 0x88, 0x13, 0xa1, 0xf4, 0x88, 0x40, 0x8b, 0xb8, 0x70, 0x41, 0xdb, 0x78,
	0x95, 0xac, 0xda, 0xd8, 0x23, 0x7b, 0x03, 0x75, 0x4f, 0xdc, 0xf9, 0x49, 0xdc, 0xf9, 0x5d, 0x68,
	0x67, 0x1d, 0xb3, 0x55, 0x7a, 0xe8, 0x6d, 0xdf, 0x9b, 0x9d, 0xe7, 0xf7, 0xc6, 0xb3, 0x30, 0x39,
	0x97, 0xcb, 0x0b, 0x55, 0x16, 0x39, 0xd6, 0x95, 0xa9, 0x78, 0x28, 0x51, 0x67, 0xbf, 0x19, 0x44,
	0x5f, 0x1b, 0x55, 0xf3, 0x43, 0x08, 0x74, 0x91, 0xb2, 0x19, 0x9b, 0x0f, 0x45, 0xa0, 0x0b, 0x9e,
	0xc3, 0x81, 0x44, 0xfc, 0xbe, 0x91, 0x98, 0x06, 0xb3, 0x70, 0x3e, 0x3a, 0x79, 0x90, 0x4b, 0xd4,
	0xb9, 0xbd, 0x9b, 0x2f, 0x10, 0x3f, 0x4a, 0x3c, 0x2b, 0x4d, 0xdd, 0x8a, 0x81, 0x24, 0x30, 0x3d,
	0x85, 0x91, 0x47, 0xf3, 0x23, 0x08, 0x2f, 0x54, 0xdb, 0xe9, 0xd9, 0x23, 0x7f, 0x0c, 0xf1, 0x0f,
	0x79, 0xb9, 0x55, 0x69, 0x30, 0x63, 0xf3, 0xd1, 0x49, 0x42, 0x72, 0x0b, 0x44, 0xe1, 0xe8, 0xb7,
	0xc1, 0x1b, 0x96, 0xfd, 0x65, 0x10, 0x2e, 0x10, 0xf7, 0xcc, 0xdc, 0x87, 0xd8, 0x68, 0x73, 0xe9,
	0x7a, 0x87, 0xc2, 0x01, 0x3e, 0x83, 0x51, 0xa1, 0x9a, 0x65, 0xad, 0xd1, 0xe8, 0xaa, 0x4c, 0x43,
	0xaa, 0xf9, 0x14, 0x7f, 0x01, 0x09, 0xca, 0x95, 0xa2, 0x14, 0x91, 0x97, 0x62, 0x81, 0x98, 0x7f,
	0x96, 0x2b, 0xd5, 0xa7, 0x38, 0x40, 0x87, 0xa6, 0x67, 0x30, 0xf6, 0x0b, 0xb7, 0xe4, 0x78, 0x72,
	0x33, 0xc7, 0x90, 0x04, 0x6d, 0x8f, 0x1f, 0xe4, 0x0f, 0x83, 0xc8, 0x72, 0x7b, 0x49, 0x8e, 0x20,
	0x2c, 0xb7, 0x1b, 0xea, 0x8d, 0x85, 0x3d, 0xf2, 0x77, 0x30, 0x59, 0x56, 0x1b, 0xac, 0x4a, 0x55,
	0x1a, 0x32, 0x1a, 0x92, 0xd1, 0x87, 0xbd, 0x6e, 0x7e, 0xba, 0x2b, 0xf7, 0x76, 0xc7, 0x4b, 0x8f,
	0x9a, 0x7e, 0x82, 0x7b, 0x7b, 0x57, 0x6e, 0x31, 0xfe, 0xf4, 0xa6, 0xf1, 0x43, 0xfa, 0x40, 0xdf,
	0xe8, 0xbb, 0x6f, 0x61, 0xd8, 0xf3, 0x7b, 0x09, 0x9e, 0x43, 0x82, 0x55, 0xa3, 0x69, 0xe4, 0x4e,
	0x69, 0xe2, 0xac, 0x76, 0xa4, 0xe8, 0xcb, 0xfc, 0x11, 0x44, 0x8d, 0xbe, 0x56, 0xf4, 0x67, 0x76,
	0x93, 0xfa, 0xa2, 0xaf, 0x95, 0x20, 0x9a, 0x73, 0x88, 0x64, 0xbd, 0x6a, 0xd2, 0x88, 0xb4, 0xe9,
	0x9c, 0x3d, 0x83, 0x64, 0x27, 0xc4, 0xc7, 0xc0, 0xae, 0xe8, 0xc3, 0xb1, 0x60, 0x57, 0x16, 0xb5,
	0xdd, 0xdc, 0x58, 0x9b, 0xbd, 0x86, 0xc8, 0x2a, 0xf1, 0x63, 0x18, 0xac, 0x95, 0x5e, 0xad, 0x4d,
	0x77, 0xb1, 0x43, 0x76, 0x63, 0x7e, 0xea, 0xc2, 0xac, 0xbb, 0x0e, 0x07, 0xb2, 0x5f, 0x0c, 0xa2,
	0x0f, 0xd2, 0x48, 0xfe, 0x12, 0x92, 0x6d, 0xa3, 0x6a, 0x9a, 0x37, 0xa3, 0x79, 0x1f, 0x93, 0x3b,
	0x5b, 0xa4, 0x1d, 0xff, 0xbf, 0x19, 0x5b, 0x87, 0xec, 0x66, 0xf8, 0x85, 0xbb, 0x6e, 0x86, 0xed,
	0xf1, 0x66, 0xfb, 0x3e, 0xfe, 0x66, 0xdf, 0xdd, 0xf9, 0x80, 0xde, 0xe0, 0xab, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0x08, 0x8c, 0x9c, 0x94, 0x03, 0x00, 0x00,
}
