apiVersion: v1
kind: Service
metadata:
  name: monitor
spec:
  selector:
    app: monitor
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30002
  type: NodePort

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: react_lab/monitor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
